# Generated by Django 4.1.7 on 2023-04-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='image/%Y/%m/%d')),
                ('price', models.FloatField()),
                ('diagonal', models.FloatField()),
                ('SSD_Volume', models.IntegerField()),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('exist', models.BooleanField(default=True)),
            ],
        ),
    ]
