# Generated by Django 4.1.7 on 2023-04-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronicAccessories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronic',
            name='exist',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
