# Generated by Django 4.1.7 on 2023-05-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronicAccessories', '0002_alter_electronic_exist_alter_electronic_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electronic',
            options={'ordering': ['title'], 'verbose_name': 'Ноутбук', 'verbose_name_plural': 'Ноутбуки'},
        ),
        migrations.AlterField(
            model_name='electronic',
            name='SSD_Volume',
            field=models.IntegerField(verbose_name='Объем SSD'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='date_update',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='diagonal',
            field=models.FloatField(verbose_name='Диагональ'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='exist',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='photo',
            field=models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='price',
            field=models.FloatField(default=10000, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='title',
            field=models.CharField(default='laptop', max_length=150, verbose_name='Наименование'),
        ),
    ]
