# Generated by Django 4.1.7 on 2023-05-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronicAccessories', '0004_alter_electronic_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronic',
            name='price',
            field=models.FloatField(default=10000, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='title',
            field=models.CharField(default='Ноутбук', max_length=150, verbose_name='Наименование'),
        ),
    ]
