# Generated by Django 4.1.7 on 2023-05-08 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronicAccessories', '0005_alter_electronic_price_alter_electronic_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование поставщика')),
                ('representative_firstname', models.CharField(max_length=150, verbose_name='Имя представителя поставщика')),
                ('representative_lastname', models.CharField(max_length=150, verbose_name='Фамилия представителя поставщика')),
                ('representative_patronymic', models.CharField(max_length=150, verbose_name='Отчество представителя поставщика')),
                ('exist', models.BooleanField(default=True, verbose_name='Сотрудничество')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='electronic',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='electronicAccessories.supplier'),
        ),
    ]
