# Generated by Django 4.1.7 on 2023-05-08 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronicAccessories', '0007_order_alter_electronic_supplier_pos_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('date_printout', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания чека')),
                ('address_printout', models.CharField(max_length=200, verbose_name='Адрес создания чека')),
                ('terminal', models.CharField(max_length=20, verbose_name='Код терминала')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='electronicAccessories.order')),
            ],
        ),
    ]
