# Generated by Django 4.1.7 on 2023-05-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronicAccessories', '0008_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['terminal', 'date_printout'], 'verbose_name': 'Чек', 'verbose_name_plural': 'Чеки'},
        ),
    ]
