# Generated by Django 4.1.7 on 2023-05-09 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronicAccessories', '0009_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='electronicAccessories.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'создан'), ('2', 'отменен'), ('3', 'согласован'), ('4', 'в пути'), ('5', 'завершен')], max_length=200, verbose_name='Состояние заказа'),
        ),
    ]
